In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf


In [2]:
test = np.array(range(50))

In [3]:
test = np.random.rand(50,2)
test

array([[0.71933246, 0.30699024],
       [0.45969336, 0.58027787],
       [0.97253918, 0.8321803 ],
       [0.18055788, 0.33959309],
       [0.5143604 , 0.58743542],
       [0.99896596, 0.39347332],
       [0.32320394, 0.24493114],
       [0.483117  , 0.08897304],
       [0.80488552, 0.78790011],
       [0.84948284, 0.91833845],
       [0.96277589, 0.94487518],
       [0.67358593, 0.72963004],
       [0.38858622, 0.90436072],
       [0.26374024, 0.52602198],
       [0.69938767, 0.43703529],
       [0.92019102, 0.42736821],
       [0.36232453, 0.96996169],
       [0.48288331, 0.41651497],
       [0.76605097, 0.18309431],
       [0.00601503, 0.4306706 ],
       [0.07497956, 0.20097226],
       [0.50390682, 0.78592984],
       [0.54459027, 0.58355926],
       [0.89745403, 0.51849059],
       [0.98915495, 0.51311279],
       [0.43104555, 0.89770134],
       [0.26771163, 0.70727602],
       [0.27502382, 0.92471516],
       [0.38890477, 0.8534801 ],
       [0.60358761, 0.69122013],
       [0.

In [4]:
next(iter(tf.keras.preprocessing.timeseries_dataset_from_array \
(test, targets = test,sequence_length=10, sampling_rate=2, sequence_stride=3, shuffle=False)))


2021-07-23 17:21:05.255645: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-23 17:21:05.329726: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-07-23 17:21:05.330316: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 1800000000 Hz


(<tf.Tensor: shape=(11, 10, 2), dtype=float64, numpy=
 array([[[0.71933246, 0.30699024],
         [0.97253918, 0.8321803 ],
         [0.5143604 , 0.58743542],
         [0.32320394, 0.24493114],
         [0.80488552, 0.78790011],
         [0.96277589, 0.94487518],
         [0.38858622, 0.90436072],
         [0.69938767, 0.43703529],
         [0.36232453, 0.96996169],
         [0.76605097, 0.18309431]],
 
        [[0.18055788, 0.33959309],
         [0.99896596, 0.39347332],
         [0.483117  , 0.08897304],
         [0.84948284, 0.91833845],
         [0.67358593, 0.72963004],
         [0.26374024, 0.52602198],
         [0.92019102, 0.42736821],
         [0.48288331, 0.41651497],
         [0.00601503, 0.4306706 ],
         [0.50390682, 0.78592984]],
 
        [[0.32320394, 0.24493114],
         [0.80488552, 0.78790011],
         [0.96277589, 0.94487518],
         [0.38858622, 0.90436072],
         [0.69938767, 0.43703529],
         [0.36232453, 0.96996169],
         [0.76605097, 0.183094

In [5]:
test

array([[0.71933246, 0.30699024],
       [0.45969336, 0.58027787],
       [0.97253918, 0.8321803 ],
       [0.18055788, 0.33959309],
       [0.5143604 , 0.58743542],
       [0.99896596, 0.39347332],
       [0.32320394, 0.24493114],
       [0.483117  , 0.08897304],
       [0.80488552, 0.78790011],
       [0.84948284, 0.91833845],
       [0.96277589, 0.94487518],
       [0.67358593, 0.72963004],
       [0.38858622, 0.90436072],
       [0.26374024, 0.52602198],
       [0.69938767, 0.43703529],
       [0.92019102, 0.42736821],
       [0.36232453, 0.96996169],
       [0.48288331, 0.41651497],
       [0.76605097, 0.18309431],
       [0.00601503, 0.4306706 ],
       [0.07497956, 0.20097226],
       [0.50390682, 0.78592984],
       [0.54459027, 0.58355926],
       [0.89745403, 0.51849059],
       [0.98915495, 0.51311279],
       [0.43104555, 0.89770134],
       [0.26771163, 0.70727602],
       [0.27502382, 0.92471516],
       [0.38890477, 0.8534801 ],
       [0.60358761, 0.69122013],
       [0.

In [6]:
for x in tf.keras.preprocessing.timeseries_dataset_from_array \
(test, targets = test,sequence_length=10, sampling_rate=1, sequence_stride=3, shuffle=False) :
    print(x)

(<tf.Tensor: shape=(14, 10, 2), dtype=float64, numpy=
array([[[0.71933246, 0.30699024],
        [0.45969336, 0.58027787],
        [0.97253918, 0.8321803 ],
        [0.18055788, 0.33959309],
        [0.5143604 , 0.58743542],
        [0.99896596, 0.39347332],
        [0.32320394, 0.24493114],
        [0.483117  , 0.08897304],
        [0.80488552, 0.78790011],
        [0.84948284, 0.91833845]],

       [[0.18055788, 0.33959309],
        [0.5143604 , 0.58743542],
        [0.99896596, 0.39347332],
        [0.32320394, 0.24493114],
        [0.483117  , 0.08897304],
        [0.80488552, 0.78790011],
        [0.84948284, 0.91833845],
        [0.96277589, 0.94487518],
        [0.67358593, 0.72963004],
        [0.38858622, 0.90436072]],

       [[0.32320394, 0.24493114],
        [0.483117  , 0.08897304],
        [0.80488552, 0.78790011],
        [0.84948284, 0.91833845],
        [0.96277589, 0.94487518],
        [0.67358593, 0.72963004],
        [0.38858622, 0.90436072],
        [0.26374024, 0.5

In [7]:
for x in tf.keras.preprocessing.timeseries_dataset_from_array \
(test, targets = test,sequence_length=10, sampling_rate=1, sequence_stride=3, shuffle=False) :
    print(x)

(<tf.Tensor: shape=(14, 10, 2), dtype=float64, numpy=
array([[[0.71933246, 0.30699024],
        [0.45969336, 0.58027787],
        [0.97253918, 0.8321803 ],
        [0.18055788, 0.33959309],
        [0.5143604 , 0.58743542],
        [0.99896596, 0.39347332],
        [0.32320394, 0.24493114],
        [0.483117  , 0.08897304],
        [0.80488552, 0.78790011],
        [0.84948284, 0.91833845]],

       [[0.18055788, 0.33959309],
        [0.5143604 , 0.58743542],
        [0.99896596, 0.39347332],
        [0.32320394, 0.24493114],
        [0.483117  , 0.08897304],
        [0.80488552, 0.78790011],
        [0.84948284, 0.91833845],
        [0.96277589, 0.94487518],
        [0.67358593, 0.72963004],
        [0.38858622, 0.90436072]],

       [[0.32320394, 0.24493114],
        [0.483117  , 0.08897304],
        [0.80488552, 0.78790011],
        [0.84948284, 0.91833845],
        [0.96277589, 0.94487518],
        [0.67358593, 0.72963004],
        [0.38858622, 0.90436072],
        [0.26374024, 0.5

In [8]:
import asyncio

async def test() :
    return 5

yala = [asyncio.create_task(test()) for i in range(50)]

In [9]:
await asyncio.gather(*yala)

[5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5]

In [10]:
from datalib import BinanceTradeLoader 
import math
import numpy as np
import pandas as pd
import seaborn as sns
from calendar import monthrange
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import asyncio

In [11]:
resample_interval = 1000 #milliseconds
trade_intervals = 60 #resample_intervals
local_cache_path = "/media/corvin/BigData/Crypto/binance/"
trade_loader = BinanceTradeLoader(local_cache_path)

In [12]:
async def make_monthly_volume_vwap_and_imbalance(symbol, month, year, resample_interval) :
    num_days = monthrange(year, month)[1]
    data_tasks = [asyncio.create_task(make_daily_volume_vwap_and_imbalance(symbol, day, month, year, resample_interval)) for day in range(1,num_days + 1)]
#     return await asyncio.gather(*data_tasks)
#     data = asyncio.create_task(
    return pd.concat(await asyncio.gather(*data_tasks)).reset_index(drop = True)

async def make_daily_volume_vwap_and_imbalance(symbol, day, month, year, resample_interval) :
    trades = trade_loader.load_daily_trades_usdt_margined(symbol, day, month, year)
    resampled = make_volume_vwap_and_imbalance(trades, resample_interval)
    del trades
    return resampled
def make_volume_vwap_and_imbalance(trades, resample_interval = 1000) :
    trades["buy_usdt_volume"] = trades["price"] * trades["qty"] *(1 - trades["isBuyerMaker"])
    trades["sell_usdt_volume"] = trades["price"] * trades["qty"] *trades["isBuyerMaker"]
    trades["usdt_volume"] = trades["price"] * trades["qty"]
    resampled =  trades.resample(f'{resample_interval}ms', on = "time").agg({"buy_usdt_volume" : np.sum, "sell_usdt_volume" : np.sum, "usdt_volume" : np.sum, "qty" : np.sum}).reset_index()
    resampled["buy_percentage"] = resampled["buy_usdt_volume"] / (resampled["buy_usdt_volume"] + resampled["sell_usdt_volume"])
    resampled["vwap"] = resampled["usdt_volume"] / resampled["qty"]
    resampled["vwap"].fillna(method="ffill", inplace = True)
    resampled["buy_percentage"].fillna(0.5, inplace = True)
    return resampled.drop(columns = ["usdt_volume", "buy_usdt_volume", "sell_usdt_volume"])
#     return  resampled


In [20]:
import time
start_time = time.time()
await make_monthly_volume_vwap_and_imbalance("EOS", 6,2021, resample_interval)
print ("My program took", time.time() - start_time, "to run")

My program took 27.32027316093445 to run


In [19]:
print ("My program took", time.time() - start_time, "to run")

My program took 24.279144763946533 to run
